import type { Metadata } from 'next';
import { DM_Sans, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { TRPCReactProvider } from '@/server/trpc/client';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const DMSans = DM_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Mi Expo',
  icons: {
    icon: '/vercel.svg',
  },
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang='en'>
        <body className={`${DMSans.className} antialiased h-[100dvh]`}>
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
